import './globals.css'
import { Montserrat } from 'next/font/google'
import Nav from '@/components/Nav'
import Footer from '@/components/Footer'
import Script from 'next/script'
import { Providers } from './globalRedux/provider'


const mont = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Next-SHREDDEPOT',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={mont.className}>
            {children}
            {/* <Footer /> */}
        </body>
      </Providers>


      <Script 
        type="module" 
        src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
      />
      <Script 
        nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"
      />
    </html>
  )
}
