// 'use client'

import './globals.css'
import { Montserrat } from 'next/font/google'
import Script from 'next/script'
import { Providers } from './globalRedux/provider'


const mont = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Next-SHREDDEPOT',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
          <body className={mont.className}>
          <Providers>

              {children}
              {/* <Footer /> */}
          </Providers>
          </body>


      <Script 
        type="module" 
        src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
      />
      <Script 
        nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"
      />
    </html>
  )
}
